name: CI on NVIDIA GPU

on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  ci:
    if: >
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/run-nvidia-ci') &&
      github.event.comment.author_association == 'OWNER'
    runs-on: ubuntu-latest
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: uv sync --group dev
    - name: Run tests on NVIDIA GPU
      run: uv run modal run -m ci.nvidia
